Query the most common UploadWizard exceptions & errors
This should generate results like: (for exceptions)

date    message total
2017-02-26      TypeError: invalid 'in' operand obj     20
2017-02-26      Uncaught TypeError: Cannot read property 'getPrefixedText' of null      5
2017-02-26      TypeError: null is not an object (evaluating 'elt.parentNode')  5
2017-02-26      Uncaught TypeError: Cannot read property '0' of undefined       1
2017-02-26      Uncaught Error: module already implemented: ext.gadget.UTCLiveClock     1
2017-02-26      Uncaught URIError: URI malformed        1
2017-02-27      TypeError: invalid 'in' operand obj     11
2017-02-27      allocation size overflow        1
2017-02-27      Uncaught Error: Invalid LatLng object: (NaN, 50)        1
2017-02-28      TypeError: invalid 'in' operand obj     16
2017-02-28      SyntaxError: missing ; before statement 2
2017-02-28      Uncaught TypeError: itemWidgets[i].resetInitiallyUnseen is not a function       1
2017-02-28      ReferenceError: ta is not defined       1

Bug: T156694
Bug: T159233
Change-Id: Ic6e6a6bb5c6fd0eccf4e1727eca3181800905b00